version: "3.9"
services:
  db:
    image: postgres:13
    container_name: pantrydb
    env_file:
      - db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
  web:
    build: .
    container_name: pantryapi
    env_file:
      - web.env
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db

volumes:
  postgres_data: